In [1]:
import numpy as np
import torch

In [3]:
a = np.array(1)
b = torch.tensor(1)

print(a)
print(b)

1
tensor(1)


In [4]:
print(type(a), '--', type(b), '--', a.shape, '--', b.shape)

<class 'numpy.ndarray'> -- <class 'torch.Tensor'> -- () -- torch.Size([])


In [5]:
b.shape

torch.Size([])

### Performing mathematical operations in numpy

In [6]:
a = np.array(2)
b = np.array(1)
print(a, b)

2 1


In [7]:
# addition
print(a+b)

# substration
print(b - a)

# multiplication
print(a*b)

# division
print(a/b)

3
-1
2
2.0


### Mathematical operations in Pytorch

In [8]:
a = torch.tensor(2)
b = torch.tensor(1)
print(a, b)

tensor(2) tensor(1)


In [9]:
# addition
print(a+b)

# substration
print(b -a)

# multiplication
print(b*a)

# division
print(a/b)




tensor(3)
tensor(-1)
tensor(2)
tensor(2)


In [10]:
# Matrix initializations
a = np.zeros((3,3))
print(a, '---', a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] --- (3, 3)


In [11]:
a = torch.zeros((3, 3))
print(a, '---', a.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) --- torch.Size([3, 3])


# randomly initialize the weight of models using numpy as well as pytorch

In [12]:
# setting the random seed of numpy
np.random.seed(42)

# matrix of random numbers
a = np.random.randn(3,3)
print(a)

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]


In [13]:
# setting the random seed of torch
torch.manual_seed(42)

# initialize random matrix
a = torch.randn(3,3)
print(a)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])


In [14]:
np.random.seed(42)
a = np.random.randn(3,3)
b = np.random.randn(3,3)

In [15]:
print(np.add(a,b), '\n')

print(np.subtract(a,b), '\n')

print(np.dot(a, b), '\n')

print(np.divide(a,b), '\n')

[[ 1.0392742  -0.60168199  0.18195878]
 [ 1.76499213 -2.14743362 -1.95905479]
 [ 1.01692529 -0.24539639 -0.15522705]] 

[[-0.04584589  0.32515339  1.11341829]
 [ 1.28106758  1.67912687  1.49078088]
 [ 2.14150034  1.78026585 -0.78372172]] 

[[-0.12814468 -0.62164688  0.21069439]
 [ 0.90133115 -0.02065676 -0.3790019 ]
 [ 1.30648762 -1.7246546  -2.20677932]] 

[[ 0.9155008   0.29835784 -1.39069607]
 [ 6.29449313  0.12238321  0.13573803]
 [-2.80855031 -0.75771243 -1.49396459]] 



In [16]:
# Matrix transpose
print(a, '\n')
print(np.transpose(a))

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]] 

[[ 0.49671415  1.52302986  1.57921282]
 [-0.1382643  -0.23415337  0.76743473]
 [ 0.64768854 -0.23413696 -0.46947439]]


In [2]:
# pytorch

torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)

In [3]:
print(torch.add(a,b), '\n')

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]]) 



In [4]:
print(torch.sub(a, b), '\n')

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]]) 



In [5]:
print(torch.div(a, b))

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])


In [6]:
print(torch.mm(a, b), '\n')

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]]) 



In [7]:
# Calculating transpose in pytorch
print(a, '\n')

torch.t(a)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]]) 



tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])

In [10]:
# Concatenating two tensors

a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([[5,6], [7,8]])
print(a, '\n\n', b)

tensor([[1, 2],
        [3, 4]]) 

 tensor([[5, 6],
        [7, 8]])


In [12]:
# concatenate vertically
torch.cat((a, b))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [13]:
# concatenate horizontally
torch.cat((a,b), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

### Reshaping

In [14]:
torch.manual_seed(42)

a = torch.randn(2, 4)
print(a)
a.shape

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380]])


torch.Size([2, 4])

In [17]:
b = a.reshape(1, 8)
print(b)
b.shape

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380]])


torch.Size([1, 8])

In [18]:
c = b.reshape(8, 1)
print(c)
c.shape

tensor([[ 0.3367],
        [ 0.1288],
        [ 0.2345],
        [ 0.2303],
        [-1.1229],
        [-0.1863],
        [ 2.2082],
        [-0.6380]])


torch.Size([8, 1])

### Converting a numpy array to tensor 

In [19]:
a = np.array([[1,2], [3,4]])
print(a, '\n')

tensor = torch.from_numpy(a)
print(tensor)

[[1 2]
 [3 4]] 

tensor([[1, 2],
        [3, 4]])


### Common Pytorch Modules 

In [28]:
a = torch.ones((2,2), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [29]:
b = a + 5
c = b.mean()

print(b, c)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>) tensor(6., grad_fn=<MeanBackward0>)


In [31]:
c.backward()
print(a.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [ ]:
# Optim module
from torch import optim

## Buiding a nuearal network from scratch in Pytorch

In [33]:
# input
X = torch.Tensor([[1,0,1,0], [1,0,1,1], [0,1,0,1]])

# output
y = torch.Tensor([[1],[1],[0]])

print(X)
print(y)

tensor([[1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 1., 0., 1.]])
tensor([[1.],
        [1.],
        [0.]])


In [34]:
# Segmoid function
def sigmoid(x):
    return 1/(1+ torch.exp(-x))
    
# Derivative of Sigmoid function
def derivatives_sigmoid(x):
    return x*(1 - x)

In [41]:
X.shape[1]

4

In [38]:
# Variable initialization

epoch = 7000
lr = 0.1
inputlayer_neurons = X.shape[1]
hiddenlayer_neurons = 3
output_neurons = 1

# weight and bias initializations
wh = torch.randn(inputlayer_neurons, hiddenlayer_neurons).type(torch.FloatTensor)
bh = torch.randn(1, hiddenlayer_neurons).type(torch.FloatTensor)
wout = torch.randn(hiddenlayer_neurons, output_neurons)
bout = torch.randn(1, output_neurons)

In [51]:
wh

tensor([[-1.0368, -0.7592,  2.7542],
        [ 0.6280,  1.5146, -1.8436],
        [ 0.0655, -1.7250,  1.3391],
        [ 0.3190,  0.1342, -0.8630]])

In [53]:
X

tensor([[1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 1., 0., 1.]])

In [55]:
-(1.0368*1) + (1*0.0655)

-0.9712999999999999

In [59]:
torch.mm(X, wh)

tensor([[-0.9713, -2.4841,  4.0933],
        [-0.6523, -2.3499,  3.2303],
        [ 0.9470,  1.6487, -2.7065]])

In [60]:
out = sigmoid(_)

In [65]:
# out[0] tensor([0.2746, 0.0770, 0.9836])
out

tensor([[0.2746, 0.0770, 0.9836],
        [0.3425, 0.0871, 0.9620],
        [0.7205, 0.8387, 0.0626]])

In [62]:
wout

tensor([[-1.2586],
        [-2.6061],
        [ 5.4091]])

In [70]:
out2 = torch.mm(out, wout) +bout
out2

tensor([[ 4.3764],
        [ 4.1477],
        [-3.1519]])

In [71]:
sigmoid(out2)

tensor([[0.9876],
        [0.9844],
        [0.0410]])

In [39]:
for i in range(epoch):
    hidden_layer_input1 = torch.mm(X, wh)
    hidden_layer_input = hidden_layer_input1 + bh
    hidden_layer_activations = sigmoid(hidden_layer_input)
    
    output_layer_input1 = torch.mm(hidden_layer_activations, wout)
    output_layer_input = output_layer_input1 + bout
    output = sigmoid(output_layer_input)
    
    E = y - output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hidden_layer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = torch.mm(d_output, wout.t())
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += torch.mm(hidden_layer_activations.t(), d_output) *lr
    bout += d_output.sum()* lr
    wh += torch.mm(X.t(), d_hiddenlayer) * lr
    bh += d_output.sum() * lr

In [40]:
print('actual: \n', y, '\n')
print('Predicted:\n', output)

actual: 
 tensor([[1.],
        [1.],
        [0.]]) 

Predicted:
 tensor([[0.9827],
        [0.9768],
        [0.0289]])


In [90]:
sigmoid(torch.Tensor([8]))

tensor([0.9997])